### ISSUE TITLE
development environment

### ISSUE THREAD

**Issue by sunshinesjw1** [mr7495/RetinaNet_Motile_objects_Detection#1]
Hello, could you explain the development environment used in your code? such as tensorflow/keras version.

**Comment by mr7495** [comment]
Hello
Sorry for the late reply.The environment is built based on TensorFlow 1.15 and Keras 2.31.
RegradsMohammad

    On Tuesday, December 8, 2020, 07:47:07 AM GMT+3:30, sunshinesjw1 <notifications@github.com> wrote:  
 
 


Hello, could you explain the development environment used in your code? such as tensorflow/keras version.
